aws_access_key    = "xxxxxxxxxxxxxxxxx"
aws_secret_key    = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
aws_region      = "us-east-1"
s3-bucket-lambda-code = "non-resized-image-ashishmundle1-2026"
s3-bucket-dest    = "resized-images-ashishmundle1-2026"
sns-name       = "Resized-Image-SNS-Topic"
mail-id       = "ashisxxxxxxx@gmail.com"